### ISSUE TITLE
support `source-repository` sections

### ISSUE THREAD

**Issue by soenkehahn** [sol/cabalize#1]

**Comment by sol** [comment]
While support for `source-repository` in general will be useful at some point, I'm currently most interested in implementing a nice way for github.  First I though we could do something like:

```yaml
source-repository:
  github: sol/cabalize
```

But now I'm inclined to just make it

```yaml
github: sol/cabalize
```
instead.

@soenkehahn What do you think?

**Comment by soenkehahn** [comment]
I would prefer the latter. Or maybe even `sources: sol/cabalize`.

**Comment by sol** [comment]
I think it's important to be prepared for future changes in the ecosystem + I hope some time there will be something even more awesome than github.  This is why I implemented `github: ...` now.

https://github.com/sol/cabalize/commit/99469a52829a044a286365bb942ae7789409bec9

**Comment by soenkehahn** [comment]
:+1:
